code-quality:
  image: python:3.11
  stage: test
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - /root/.local/bin/poetry install
    - apt-get update && apt-get install -y nodejs npm
    - npm install --prefix frontend
  script:
    - /root/.local/bin/poetry run pre-commit run --all-files
