code-quality:
  image: python:3.11
  stage: test
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - /root/.local/bin/poetry install
  script:
    - pre-commit run --all-files
