name: codequality
run-name: Test lint / format / typecheck
on: [push]
jobs:
  codequality:
    runs-on: ubuntu-latest
    container: python:3.11
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -ex
          curl -sSL https://install.python-poetry.org | python3 -
          /github/home/.local/bin/poetry install
          apt-get update && apt-get install -y nodejs npm git
          npm install --prefix frontend
          pwd
          echo $GITHUB_WORKSPACE
          ls
          /github/home/.local/bin/poetry run pre-commit run --all-files
