name: deploy
run-name: Deploy to PyPI
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: python:3.11
    environment: release
    needs: codequality
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      - uses: actions/checkout@v4
      - name: Deploy
        run: |
          set -ex
          curl -sSL https://install.python-poetry.org | python3 -
          /github/home/.local/bin/poetry install
          /github/home/.local/bin/poetry build
          /github/home/.local/bin/poetry run twine upload dist/*
